### PR TITLE
Update the dashboard URL

### PR DESCRIPTION
**Pull request by hyperbolic2346**
Fixes https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/562

### CODE REVIEW

**Comment by ktsakalozos** [comment]
Thank you @hyperbolic2346 for the PR. Can you please update this readme as well: https://github.com/juju-solutions/bundle-canonical-kubernetes/blob/master/fragments/k8s/cdk/README.md

**Comment by hyperbolic2346** [comment]
@ktsakalozos done. Are we sure this is http and not https? It just caught my eye.

**Comment by Cynerva** [comment]
The URL you've got is correct: `http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/`

We use `http` when talking to `kubectl proxy`, which proxies through kube-apiserver, which uses `https` when talking to kubernetes-dashboard.

**Comment by kwmonroe** [comment]
Pretty sure it's http.  That's what the dashboard [readme](https://github.com/kubernetes/dashboard/blob/master/README.md) says too:

```
Now access Dashboard at:

http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
```

**Pull request merged**
